---
title: "ISPOR Europe 2021: number of goals vs number of attainment levels"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Important dates

* Deadline: Tuesday, June 29 2021
* Acceptance notification: Tuesday, August 17 2021
* Conference: December 1-3 2021

# Guidelines

* Title in title case
* Study approach:
    * Decision Modeling & Simulation
* Choose a topics and subtopics, some relevant ones to this abstract:
    * Clinical Outcomes
        * Clinician Report Outcomes
    * Methodological & Statistical Research
        * **Modeling & Simulation**
    * Patient-Centered Research
        * Stated Preference & Patient Satisfaction
        * Patient-reported Outcomes & Quality of Life Outcomes
* Specific disease/specialized treatment area
    * Can select up to 4 that best describes your research
    * You can choose "multiple" if one choice does not apply
* 300 words or fewer
* No tables or graphs
* Research presented at a previous ISPOR meeting is not allowed

\newpage

# Abstract

Title: Distributional assumptions of goal attainment scaling data: a simulation study

Authors: Taylor, Justin, Kari, Sanja, Susan, Ken

## Background

Goal attainment scaling (GAS) is a patient-centric outcome measure that captures meaningful change through personally identified goals of treatment.
Typically, each patient sets a minimum of three goals, and for each goal a 5-point attainment scale is defined to describe possible outcomes, with the midpoint of the scale representing the "expected outcome" under the intervention.
A key assumption in traditional GAS analysis is that the distribution of scores on the scale approximate a normal distribution.
Using data simulation techniques, we investigated the implications of this assumption.

## Methods

We employed a probabilistic latent variable model introduced by Urach et al. (2019) for generating GAS data.
We varied the number of subjects $m$ (40, 60, 80; randomly allocated to control or treatment group with equal probability), the treatment effect size $\delta$ (0.3, 0.5, 0.7, 0.9 and 1.1), and the number of goals per subject $n$ (from 1 to 5 goals).
Latent goal scores were discretized into 5-point scales using two sets of thresholds: "uniform" thresholds were equally spaced so to return a uniform distribution of scores, and "normal" thresholds were spaced so to return an approximately normal distribution of scores.
For each set of parameters, 1000 trials were simulated and a two-sided $t$-test was performed on summary T-scores.
Power was computed as the percentage of simulations detecting a significant treatment effect at $\alpha$ = 0.05.

## Results

The statistical power did not vary significantly whether using uniform or normal thresholds -- less than 1% difference for most parameter combinations.
There was a consistent difference, however, in the estimated effect size (difference between treatment and control group scores).
Across all parameter combinations, the uniform thresholds gave standardized effect sizes
between 1.7 and 4.6 points higher than those with the normal thresholds.

## Conclusions

Violating the distributional assumptions of goal attainment scaling data may lead to biased estimates of treatment effect size, though it is unlikely to affect the power to detect a treatment effect.